configured_endpoints: 147
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/stainless-kwhinnery%2Fopenai-mcp-test-a8494c5592d2e93b082deb4f46d7edae80efebc63f7b6938ebeec3d0e75ca32d.yml
openapi_spec_hash: 3d16139a57fc6fabfe435db1c977a13d
config_hash: babe81e0cba5bdaa9951b6623fb4a135
